# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

saem_linear_prob_cpp <- function(psi, cols, id, design) {
    .Call(`_saemMicrobiome_saem_linear_prob_cpp`, psi, cols, id, design)
}

